### PR TITLE
New error classes and add error class to form field using django-widget-tweaks

### PR DESCRIPTION
**Pull request by Parbhat**
error

### CODE REVIEW

**Comment by chrisdev** [comment]
Our formstags has a template tag called `render_fields` also.
I've noticed the we have no tests for our own render fields tag! So I have no idea how this impact on our own native render fields tag.
Finally, why could we not add this new error stuff to our own render fields tags.

**Comment by chrisdev** [comment]
@Parbhat i don't see the need for form_tweaks when we have our own render_fields tag!

**Comment by chrisdev** [comment]
This is some code from the rsna_app. that uses the render_field tag

```
   <legend>Profile Information</legend>
                         <div class="row">
                             <div class="medium-6 columns">
                                 {% render_field form.first_name %}
                             </div>
                             <div class="medium-6 columns">
                                 {% render_field form.last_name %}
                             </div>
                         </div>
                         <div class="row">
                             <div class="medium-6 columns">
                                 {% render_field form.date_of_birth %}
                             </div>
                             <div class="medium-6 columns">
                                 {% render_field form.gender %}
                             </div>
                    </div>

```

**Comment by Parbhat** [comment]
@chrisdev I am using the current `render_field`. The `render_field` uses the template `foundation_formtags/foundation_form_field.html` which I have modified.

The foundation 6 has no `error` class as in Foundation 5 (used in RSNA site). The foundation 6 has 3 different error classes for labels, fields, and error text.

labels - `is-invalid-label`
fields - `is-invalid-input`
error text - `form-error is-visible`

The template is modified to use new error classes for labels and error text.

The purpose for using `django-widget-tweaks` is to have the ability to add classes to input fields generated by `render_field` tag. Currently in `django-foundation-formtags` there is no `error` class for form fields (In RSNA site, input field remain same in case of error). I have used the `add_error_class` filter from  `django-widget-tweaks` to add `is-invalid-input` class on input fields in case of error.

**Comment by chrisdev** [comment]
@Parbhat My question is that do we REALLY need to whole of django-widget-teaks or can we not steal some ideas from widget_tweaks to incorporate into our module. I'm worried that widget_tweaks may break in future versions of django and we'll be on to hook for this. 

Remember the PassThroughManager in django-pandas? I had model_utlls as a dependency even though I really just needed to use the passthrough manager...In hind-site, I should have just taken the PassthrougManager  code out and used it in the project!

**Comment by Parbhat** [comment]
@chrisdev I checked the docs of django-widget-tweaks and they also have a `render_field` tag. This will collide with our own `render_field` tag. We can add their `add_error_class` filter in our project to avoid the issue.

**Comment by chrisdev** [comment]
@Parbhat  this is what I've been pointing out to you two comments ago!
We have our `render_field` tag so why are we not updating it for foundation 6 and adding what is missing!!  

I'm going to create a issue to add to add `render_field` to our tests!

You've still not convinced me that we need to use `widget_tweaks`

**Comment by Parbhat** [comment]
@chrisdev Yes we do not need django-widget-tweaks. I will add a filter  `add_error_class` to meet the needs.

**Pull request merged**
